# Generated by Django 4.0.4 on 2022-04-21 00:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('author_id', models.IntegerField(primary_key=True, serialize=False)),
                ('author_name', models.CharField(max_length=255)),
                ('affiliations', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=255), size=None)),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('paper_doi', models.TextField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('publishedby', models.TextField()),
                ('author_id', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('ieee_keywords', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('authors_keywords', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('pubTopics', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('publicationNumber', models.CharField(max_length=255)),
                ('publicationDate', models.DateField()),
                ('metrics', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('refs', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('googleScholarLink', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
            ],
        ),
    ]
