# Generated by Django 4.0.4 on 2022-04-23 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PaperInfo', '0002_paper_ref_doi_alter_authors_affiliations_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paper',
            old_name='ref_doi',
            new_name='refs_doi',
        ),
    ]
